### ISSUE TITLE
why my stepper doesn't give the correct value when I tap the increment button ?

### ISSUE THREAD

**Issue by AgungLaksana** [kyleweiner/KWStepper#11]
https://stackoverflow.com/questions/54156822/why-my-stepper-doest-give-the-correct-value-when-i-tap-the-increment-button

Hi, could you please help me with this issue ?

**Comment by kyleweiner** [comment]
Hi, @AgungLaksana. Try using the provided `KWStepperDelegate` methods or callbacks instead of the `IBAction`s you've implemented. Here’s an example using the `valueChanged` callback.

```swift
stepper.valueChanged { [weak self] stepper in
    self?.counterLabel.text = "\(stepper.value)"
}
```

If you need to respond to incrementing or decrementing separately, you can add the `didIncrement` or `didDecrement` callbacks:

```swift
stepper
    .valueChanged { [weak self] stepper in
        self?.counterLabel.text = "\(stepper.value)"
    }.didDecrement { stepper in
        // Decremented
    }.didIncrement { stepper in
        // Incremented
    }
```
